[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5A"
key = "Up"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5B"
key = "Down"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5D"
key = "Left"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[1;5C"
key = "Right"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002]"
key = "RBracket"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Back"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Alt|Shift"

[general]
live_config_reload = false

[terminal]

[colors.bright]
black = "0x4C566A"
blue = "0x91B1D1"
cyan = "0x9FCCCB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xCF817A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.cursor]
cursor = "0xD8DEE9"
text = "0x2E3440"

[colors.normal]
black = "0x3B4252"
blue = "0x91B1D1"
cyan = "0x98D0E0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xCF817A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x363C48"
foreground = "0xD8DEE9"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 1
y = 0

[scrolling]
history = 10000
multiplier = 5

[selection]
semantic_escape_chars = ''',│`|:"' ()[]{}<>	#'''

[terminal.shell]
program = "/usr/bin/bash"
args = ["--login", "-c", '''tmux attach -t "(●'◡'●)" || tmux -f $HOME/nomad/tmux.conf new -s "(●'◡'●)"''']
# program = "wsl"
# args = ["--", "/usr/bin/bash", "--login", "-c", """'export NOMAD=$PWD; tmux attach -t "(●'"'"'◡'"'"'●)" || tmux -f tmux.conf new -s "(●'"'"'◡'"'"'●)"'"""]

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 108
lines = 36

[window.padding]
x = 4
y = 4
