set -g default-terminal "xterm-256color"
set -g default-shell /usr/bin/bash
set -g default-command "/usr/bin/bash --init-file bashrc"
bind-key x kill-pane
set-window-option -g mode-keys vi
set -g status-left "#S | "
set -g status-right ""
set -g status-interval 0
set -g history-limit 65536
set -g escape-time 30
set -g renumber-windows on
set -g repeat-time 1
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind k send-keys -R \; clear-history \; send-keys C-l
